updates for experiments, xgb_functions, data_preprocessing
early version of results table now being generated. 

Many datasets are returning the following error:
xgboost.core.XGBoostError: [16:34:12] D:\Build\xgboost\xgboost-0.90.git\src\metric\rank_metric.cc:200: Check failed: !auc_error: AUC: the dataset only contains pos or neg samples

unsure if dataset related or implementation related.

considering adding more extensive qcut options

need to test compatibility with rules/search modules